spring:
  application:
    name: saboteur

  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

socketio:
  server:
    hostname: localhost
    port: 8081

logging:
  level:
    org.springframework.boot.autoconfigure: error
